-- Two distinct, separately-recorded streams: runtime events and user-activity
-- audit. They are never merged. See backend-specs/03 & 04.

create table runtime_events (
    id             bigint generated by default as identity primary key,
    project_id     varchar not null references projects (id) on delete cascade,
    data_source_id varchar,
    run_id         varchar,
    type           varchar not null,
    at             timestamptz not null default now(),
    payload        jsonb not null default '{}'::jsonb
);

create table activity_events (
    id          bigint generated by default as identity primary key,
    project_id  varchar,
    actor       varchar not null,
    action      varchar not null,
    object_type varchar not null,
    object_id   varchar,
    at          timestamptz not null default now(),
    detail      jsonb not null default '{}'::jsonb
);

create index idx_runtime_events_project on runtime_events (project_id, at);
create index idx_runtime_events_run on runtime_events (run_id, at);
create index idx_activity_events_project on activity_events (project_id, at);
create index idx_activity_events_actor on activity_events (actor, at);
