export type SourceValueRow = {
  id: string;
  sourceId: string;
  path: string;
  group: "Thermal" | "Motion" | "Status" | "Quality" | "Power" | "Flow";
  dataType: "float" | "int" | "bool" | "enum";
  currentValue: string;
  updatedAt: string;
  freshness: "Live" | "Stale";
  pinned: boolean;
};

export const sourceValueRows: SourceValueRow[] = [
  {
    id: "val-01",
    sourceId: "src-01",
    path: "oven.zone[1].temp",
    group: "Thermal",
    dataType: "float",
    currentValue: "182.4 C",
    updatedAt: "09:41:12",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-02",
    sourceId: "src-01",
    path: "oven.zone[2].temp",
    group: "Thermal",
    dataType: "float",
    currentValue: "183.1 C",
    updatedAt: "09:41:10",
    freshness: "Live",
    pinned: false,
  },
  {
    id: "val-03",
    sourceId: "src-01",
    path: "line.speed",
    group: "Motion",
    dataType: "float",
    currentValue: "1.82 m/s",
    updatedAt: "09:41:11",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-04",
    sourceId: "src-01",
    path: "line.batch.id",
    group: "Status",
    dataType: "enum",
    currentValue: "BATCH-441",
    updatedAt: "09:40:58",
    freshness: "Live",
    pinned: false,
  },
  {
    id: "val-05",
    sourceId: "src-01",
    path: "alarm.state",
    group: "Status",
    dataType: "enum",
    currentValue: "Clear",
    updatedAt: "09:40:55",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-06",
    sourceId: "src-01",
    path: "power.feed.current",
    group: "Power",
    dataType: "float",
    currentValue: "12.8 A",
    updatedAt: "09:40:16",
    freshness: "Stale",
    pinned: false,
  },
  {
    id: "val-07",
    sourceId: "src-01",
    path: "quality.reject.count",
    group: "Quality",
    dataType: "int",
    currentValue: "4",
    updatedAt: "09:39:48",
    freshness: "Stale",
    pinned: false,
  },
  {
    id: "val-08",
    sourceId: "src-02",
    path: "register[120].state",
    group: "Status",
    dataType: "enum",
    currentValue: "Running",
    updatedAt: "09:41:02",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-09",
    sourceId: "src-02",
    path: "line.counter",
    group: "Flow",
    dataType: "int",
    currentValue: "14,882",
    updatedAt: "09:41:00",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-10",
    sourceId: "src-02",
    path: "jam.warning",
    group: "Status",
    dataType: "bool",
    currentValue: "false",
    updatedAt: "09:40:59",
    freshness: "Live",
    pinned: false,
  },
  {
    id: "val-11",
    sourceId: "src-02",
    path: "register[131].pressure",
    group: "Flow",
    dataType: "float",
    currentValue: "4.8 bar",
    updatedAt: "09:40:12",
    freshness: "Stale",
    pinned: false,
  },
  {
    id: "val-12",
    sourceId: "src-02",
    path: "motor.load.avg",
    group: "Power",
    dataType: "float",
    currentValue: "62 %",
    updatedAt: "09:40:09",
    freshness: "Stale",
    pinned: false,
  },
  {
    id: "val-13",
    sourceId: "src-03",
    path: "pump[2].rpm",
    group: "Motion",
    dataType: "int",
    currentValue: "1,420",
    updatedAt: "09:41:06",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-14",
    sourceId: "src-03",
    path: "batch.temp.avg",
    group: "Thermal",
    dataType: "float",
    currentValue: "74.2 C",
    updatedAt: "09:41:05",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-15",
    sourceId: "src-03",
    path: "quality.flag",
    group: "Quality",
    dataType: "enum",
    currentValue: "Review",
    updatedAt: "09:41:04",
    freshness: "Live",
    pinned: true,
  },
  {
    id: "val-16",
    sourceId: "src-03",
    path: "pump[2].state",
    group: "Status",
    dataType: "enum",
    currentValue: "Recording",
    updatedAt: "09:40:58",
    freshness: "Live",
    pinned: false,
  },
  {
    id: "val-17",
    sourceId: "src-03",
    path: "flow.m3h",
    group: "Flow",
    dataType: "float",
    currentValue: "11.4",
    updatedAt: "09:39:52",
    freshness: "Stale",
    pinned: false,
  },
  {
    id: "val-18",
    sourceId: "src-04",
    path: "backup.feed.enabled",
    group: "Status",
    dataType: "bool",
    currentValue: "false",
    updatedAt: "09:12:20",
    freshness: "Stale",
    pinned: true,
  },
  {
    id: "val-19",
    sourceId: "src-04",
    path: "backup.feed.current",
    group: "Power",
    dataType: "float",
    currentValue: "0.0 A",
    updatedAt: "09:12:20",
    freshness: "Stale",
    pinned: false,
  },
];
